// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujraisrqygavaycpictv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcmFpc3JxeWdhdmF5Y3BpY3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDc5NzEsImV4cCI6MjA3NDQ4Mzk3MX0.0uTs_i4TgwMJaPNgk_tvOTUtw4MnmCw-xcTibC7gk14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});